# Generated by Django 4.2.28 on 2026-02-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Client-generated UUID for idempotency.",
                null=True,
                unique=True,
            ),
        ),
    ]
