# Generated by Django 4.2.28 on 2026-02-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_transaction_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
